prometheus:
  prometheusSpec:
    retention: 7d
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "nfs-sc"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
grafana:
  assertNoLeakedSecrets: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: "nfs-sc"
    accessModes:
     - ReadWriteOnce
    size: 20Gi
  adminPassword: 9ijo@E6Msw*bc9QF


  grafana.ini:
    users:
      viewers_can_edit: true
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false

alertmanager:
  alertmanagerSpec: {}
