prometheus:
  prometheusSpec:
    retention: 7d
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "nfs-sc"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
  service:
    type: NodePort
    nodePort: 30090
grafana:
  assertNoLeakedSecrets: false
  persistence:
    enabled: true
    type: pvc
    storageClassName: "nfs-sc"
    accessModes:
     - ReadWriteOnce
    size: 20Gi
  adminPassword: 9ijo@E6Msw*bc9QF
  grafana.ini:
    users:
      viewers_can_edit: true
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  service:
    type: NodePort
    nodePort: 30080
alertmanager:
  service:
    type: NodePort
    nodePort: 30093
  config:
   global:
     resolve_timeout: 5m
   route:
     group_by: ['namespace']
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 12h
     receiver: "null"
     routes:
       - match:
           namespace: 'prod-iaas'
         receiver: 'iaas-monitor'
       - match:
           namespace: 'prod-paas'
         receiver: 'p2p-monitor'

         # sre
       - match_re:
           alertname: 'KubeJobFailed|KubeCPUOvercommit|KubeMemoryOvercommit|KubeVersionMismatch'
         receiver: 'null'
       - match_re:
           job: '^kube.*|apiserver|coredns|node-exporter'
         receiver: 'sre-monitor'
       - match_re:
           alertname: '^kube.*|^Kube.*'
         receiver: 'sre-monitor'
       - match:
           alertname: 'Watchdog'
         receiver: 'sre-monitor'
#        - receiver: "final-monitor"
#          matchers:
#            - severity =~ "warning|critical"
   receivers:
   - name: 'null'

   # to xinyu
   - name: 'iaas-monitor'
     slack_configs:
     - channel: 'iaas-monitor'
       api_url: 'https://hooks.slack.com/services/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'
       send_resolved: true
       title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring'
       text: >-
         {{ range .Alerts }}
           *{{ .Labels.alertname }}*: {{ .Annotations.description }}
           <@U07EBCD05E0>
         {{ end }}

   # to ween
   - name: 'p2p-monitor'
     slack_configs:
     - channel: 'p2p-monitor'
       api_url: 'https://hooks.slack.com/services/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'
       send_resolved: true
       title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring'
       text: >-
         {{ range .Alerts }}
           *{{ .Labels.alertname }}*: {{ .Annotations.description }}
           <@U087TQC1DFH>
         {{ end }}

   # to jabbok
   - name: 'sre-monitor'
     slack_configs:
     - channel: 'sre-monitor'
       api_url: 'https://hooks.slack.com/services/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'
       send_resolved: true
       title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring'
       text: >-
         {{ range .Alerts }}
           *{{ .Labels.alertname }}*: {{ .Annotations.description }}
           *ENV*: prod
           {{ if .Labels.name }}*{{ .Labels.name }}*: {{ .Labels.instance }}{{ else if .Labels.instance }}{{ .Labels.instance }}{{ end }}
           *Summary*: {{ .Annotations.summary }}
           <@U086T36673L>
         {{ end }}
