apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-read-pods
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-read-pods
subjects:
- kind: ServiceAccount
  name: fluentbit-fluent-bit
  namespace: fluentbit
roleRef:
  kind: ClusterRole
  name: fluentbit-read-pods
  apiGroup: rbac.authorization.k8s.io
